# Tool name, which can differ from the repo name
name: Parsuite

# Maintainer's name and email
maintainer:
  name: Justin Angel
  email: justin@blackhillsinfosec.com

# TTP tags with the format: <MITRE Tactic>/<Technique>
# URL for reference: https://attack.mitre.org/tactics/enterprise/
ttps: []
  
# Bulleted high level description. Please keep bullets brief.
descriptions:
  - Parse output files from various tools and frameworks.
  
# Determines if the tool can be discussed publicly
# Valid Values: true, false
public: true
