# Generated by Django 3.1.4 on 2021-01-24 21:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import nmap.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=17, validators=[nmap.models.validateAddress])),
                ('int', models.PositiveBigIntegerField(null=True, unique=True)),
                ('addrtype', models.CharField(choices=[('ipv4', 'ipv4'), ('ipv6', 'ipv6'), ('mac', 'mac')], default='ipv4', max_length=4)),
                ('vendor', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('up', 'up'), ('down', 'down'), ('unknown', 'unknown'), ('skipped', 'skipped')], max_length=7)),
                ('status_reason', models.CharField(max_length=100)),
            ],
            options={
                'history_model': nmap.models.HostHistory,
                'history_fk': 'host',
            },
        ),
        migrations.CreateModel(
            name='HostHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('up', 'up'), ('down', 'down'), ('unknown', 'unknown'), ('skipped', 'skipped')], max_length=7)),
                ('status_reason', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hostname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1000)),
                ('sha256sum', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(32)])),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portid', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=1000)),
                ('reason', models.CharField(max_length=1000)),
                ('protocol', models.CharField(choices=[('ip', 'ip'), ('tcp', 'tcp'), ('udp', 'udp'), ('sctp', 'sctp')], max_length=4)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', related_query_name='addresses', to='nmap.address')),
            ],
            options={
                'abstract': False,
                'history_model': nmap.models.PortHistory,
                'history_fk': 'port',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmap_id', models.CharField(max_length=1000)),
                ('output', models.TextField()),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='nmap.port')),
            ],
            options={
                'history_model': nmap.models.ScriptHistory,
                'history_fk': 'script',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('conf', models.CharField(max_length=1, null=True)),
                ('method', models.CharField(max_length=5, null=True)),
                ('version', models.CharField(max_length=1000, null=True)),
                ('product', models.CharField(max_length=1000, null=True)),
                ('extrainfo', models.TextField(null=True)),
                ('tunnel', models.CharField(max_length=100, null=True)),
                ('ostype', models.CharField(max_length=1000, null=True)),
                ('devicetype', models.CharField(max_length=1000, null=True)),
                ('proto', models.CharField(max_length=1000, null=True)),
                ('servicefp', models.TextField(null=True)),
                ('rpcnum', models.PositiveIntegerField(null=True)),
                ('lowver', models.PositiveIntegerField(null=True)),
                ('highver', models.PositiveIntegerField(null=True)),
                ('hostname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='nmap.hostname')),
                ('port', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='nmap.port')),
            ],
            options={
                'history_model': nmap.models.ServiceHistory,
                'history_fk': 'service',
            },
        ),
        migrations.CreateModel(
            name='ServiceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('conf', models.CharField(max_length=1, null=True)),
                ('method', models.CharField(max_length=5, null=True)),
                ('version', models.CharField(max_length=1000, null=True)),
                ('product', models.CharField(max_length=1000, null=True)),
                ('extrainfo', models.TextField(null=True)),
                ('tunnel', models.CharField(max_length=100, null=True)),
                ('ostype', models.CharField(max_length=1000, null=True)),
                ('devicetype', models.CharField(max_length=1000, null=True)),
                ('proto', models.CharField(max_length=1000, null=True)),
                ('servicefp', models.TextField(null=True)),
                ('rpcnum', models.PositiveIntegerField(null=True)),
                ('lowver', models.PositiveIntegerField(null=True)),
                ('highver', models.PositiveIntegerField(null=True)),
                ('hostname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nmap.hostname')),
                ('import_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nmap.importinfo')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmap.port')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmap.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScriptHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmap_id', models.CharField(max_length=1000)),
                ('output', models.TextField()),
                ('import_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nmap.importinfo')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmap.port')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmap.script')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portid', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=1000)),
                ('reason', models.CharField(max_length=1000)),
                ('protocol', models.CharField(choices=[('ip', 'ip'), ('tcp', 'tcp'), ('udp', 'udp'), ('sctp', 'sctp')], max_length=4)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmap.address')),
                ('import_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nmap.importinfo')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nmap.port')),
            ],
        ),
        migrations.AddConstraint(
            model_name='importinfo',
            constraint=models.UniqueConstraint(fields=('file_path', 'sha256sum'), name='unique_file_path_sha256sum'),
        ),
        migrations.AddField(
            model_name='hostname',
            name='addresses',
            field=models.ManyToManyField(related_name='hostnames', related_query_name='addresses', to='nmap.Address'),
        ),
        migrations.AddField(
            model_name='hostname',
            name='import_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nmap.importinfo'),
        ),
        migrations.AddField(
            model_name='hosthistory',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='nmap.host'),
        ),
        migrations.AddField(
            model_name='hosthistory',
            name='import_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nmap.importinfo'),
        ),
        migrations.AddField(
            model_name='address',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='nmap.host'),
        ),
        migrations.AddField(
            model_name='address',
            name='import_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nmap.importinfo'),
        ),
        migrations.AddConstraint(
            model_name='port',
            constraint=models.UniqueConstraint(fields=('portid', 'protocol', 'address', 'reason'), name='unique_address_port'),
        ),
    ]
